export default {
  mutate: [
    'packages/protocol/src/index.ts',
    'packages/plugin-sdk/src/index.ts',
    'packages/core/src/index.ts',
    'packages/core/src/plugin-graph.ts',
    'packages/core/src/transformation-state.ts',
    'packages/core/src/plugin-execution.ts',
    'packages/core/src/configuration-jsonc.ts',
    'packages/core/src/configuration-schema.ts',
    'packages/core/src/configuration-resolution.ts',
    'packages/core/src/capability-evidence.ts',
    'apps/runtime-node/src/native-plugin.ts',
    'apps/runtime-node/src/configuration.ts',
    'apps/runtime-node/src/server.ts',
  ],
  plugins: ['@stryker-mutator/vitest-runner', '@stryker-mutator/typescript-checker'],
  testRunner: 'vitest',
  checkers: ['typescript'],
  tsconfigFile: 'tsconfig.lint.json',
  coverageAnalysis: 'perTest',
  reporters: ['clear-text', 'json'],
  jsonReporter: { fileName: '.agent/reports/mutation.json' },
  thresholds: { high: 95, low: 90, break: 90 },
  incremental: true,
  incrementalFile: '.agent/evidence/stryker-incremental.json',
  tempDirName: '.agent/work/stryker',
};
